
version: '3.1'
services:
  trino-coordinator:
    container_name: trino-coordinator
    image: trinodb/trino
    ports:
      - 8080:8080
    volumes:
      - ./node.properties:/etc/trino/node.properties:ro
      - ./jvm.config:/etc/trino/jvm.config:ro
      - ./config.properties:/etc/trino/config.properties:ro

